name: hexlet-ci-app
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  tests:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v3
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ 9f4c83af-5abd-40d4-8289-4624fb4c8b1c }}
      - uses: actions/setup-node@v4
        with:
          cache: npm
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - run: make setup
      - run: make test
      - run: make lint